name: Publish wheels to PyPI

on:
  # allows running workflows manually
  workflow_dispatch:

  release:
    types: [published]

jobs:
  main:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: manylinux_x86_64
            shell: bash
          - os: macos-13
            arch: macosx_x86_64
            shell: bash
          - os: macos-14
            arch: macosx_arm64
            shell: bash
          - os: windows-latest
            arch: win_amd64
            shell: msys2 {0}
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2 (Windows only)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            base-devel
          pacboy: >-
            toolchain:p
            llvm-openmp:p
            lapack:p
            eigen3:p
            nlohmann-json:p
            netcdf:p
            hdf5:p

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        env:
          CIBW_BUILD: "cp*-${{ matrix.arch }}"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux_2_34_x86_64
          CIBW_ARCHS_MACOS: "native"
          CIBW_BEFORE_BUILD_LINUX: |
            dnf install -y libomp-devel eigen3-devel lapack-devel json-devel netcdf-devel hdf5-devel
          CIBW_BEFORE_BUILD_MACOS: |
            brew install gcc libomp eigen lapack nlohmann-json protobuf netcdf hdf5
          CIBW_ENVIRONMENT_MACOS: >
            MACOSX_DEPLOYMENT_TARGET=${{ matrix.os == 'macos-14' && '14.0' || '13.0' }}
            DYLD_LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/current/:$DYLD_LIBRARY_PATH
            FC=gfortran-14
            HDF5_ROOT=$(brew --prefix hdf5)
          CIBW_BEFORE_BUILD_WINDOWS: |
            git config --global core.autocrlf input
          CIBW_ENVIRONMENT_WINDOWS: >
            SKBUILD_CMAKE_ARGS="-G 'MinGW Makefiles';"
          CIBW_BUILD_FRONTEND: "build"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: vmecpp-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish:
    name: Publish wheels to PyPI
    if: github.event_name == 'release'
    needs: main
    runs-on: ubuntu-latest
    environment:
        name: vmecpp
    permissions:
        id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: wheelhouse

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
